name: integration-tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node16.18.0-chrome90-ff88
      options: --user 1001
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cypress
        uses: cypress-io/github-action@v6
        with:
          start: yarn start
          browser: chrome
          headless: true
          wait-on: http://localhost:4200
        env: # Or as an environment variable
          CYPRESS_URL: ${{ secrets.CYPRESS_URL }}
          CYPRESS_ID: ${{ secrets.CYPRESS_ID }}
          CYPRESS_SECRET: ${{ secrets.CYPRESS_SECRET }}
